version: "2.2"
services:
  es01: #Elasticsearch node 1
    image: docker.elastic.co/elasticsearch/elasticsearch:${VERSION}
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=${ELASTIC_SEARCH_CLUSTER_NAME}
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - eslog01:/usr/share/elasticsearch/log
    ports:
      - ${ELASTIC_PORTS}
    networks:
      - esnet

  es02: #Elasticsearch node 1
    image: docker.elastic.co/elasticsearch/elasticsearch:${VERSION}
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=${ELASTIC_SEARCH_CLUSTER_NAME}
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
      - eslog02:/usr/share/elasticsearch/log
    networks:
      - esnet

  kibana: #Kibana
    image: docker.elastic.co/kibana/kibana:${VERSION}
    container_name: kibana
    environment:
      SERVER_NAME: ${KIBANA_SERVER_NAME}
      ELASTICSEARCH_HOSTS: http://es01:${ELASTIC_PORTS}
    ports:
      - ${KIBANA_PORTS}
    networks:
      - esnet
    depends_on: 
      - es01

  logstash: #Logstash
    image: docker.elastic.co/logstash/logstash:${VERSION}
    volumes:
      - logstash:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - ${LOGSTASH_PORT}
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - esnet
    depends_on: 
      - es01

volumes:
  esdata01:
    driver: local
  eslog01:
    driver: local
  esdata02:
    driver: local
  eslog02:
    driver: local
  logstash:
    driver: local

networks:
  esnet:
