version: "2.2"
services:
  es01: #Elasticsearch node 1
    image: docker.elastic.co/elasticsearch/elasticsearch:${VERSION}
    container_name: ${ELASTICSEARCH_NODE_1}
    environment:
      - node.name=${ELASTICSEARCH_NODE_1}
      - discovery.seed_hosts=${ELASTICSEARCH_NODE_2}
      - cluster.initial_master_nodes=${ELASTICSEARCH_NODE_1},${ELASTICSEARCH_NODE_2}
      - cluster.name=${ELASTIC_SEARCH_CLUSTER_NAME}
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - ${ELASTIC_PORTS}
    networks:
      - esnet
  es02: #Elasticsearch node 1
    image: docker.elastic.co/elasticsearch/elasticsearch:${VERSION}
    container_name: ${ELASTICSEARCH_NODE_2}
    environment:
      - node.name=${ELASTICSEARCH_NODE_2}
      - discovery.seed_hosts=${ELASTICSEARCH_NODE_1}
      - cluster.initial_master_nodes=${ELASTICSEARCH_NODE_1},${ELASTICSEARCH_NODE_2}
      - cluster.name=${ELASTIC_SEARCH_CLUSTER_NAME}
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    networks:
      - esnet

  kibana: #Kibana
    image: docker.elastic.co/kibana/kibana:${VERSION}
    container_name: ${KIBANA_NAME}
    environment:
      SERVER_NAME: ${KIBANA_SERVER_NAME}
      ELASTICSEARCH_HOSTS: http://${ELASTICSEARCH_NODE_1}:${ELASTIC_PORTS}
    ports:
      - ${KIBANA_PORTS}
    networks:
      - esnet

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local

networks:
  esnet:
